### PR TITLE
Adding terminal colors (24 bit)

### PR DESCRIPTION
**Pull request by metalelf0**
This PR adds 24 bit colors for neovim terminal windows.

### CODE REVIEW

**Comment by mhartington** [comment]
Shouldn't this be covered by using the Gui colors?

**Comment by metalelf0** [comment]
@mhartington in my setup it doesn't. When Neovim is in true color mode it falls back to a default ANSI palette and the only way I've found to add terminal colors is setting these manually. I tried many different combinations but AFAIK this is the way to go (also see this issue https://github.com/chriskempson/base16-vim/issues/69). I'm using osx with iTerm2 and latest neovim master, no tmux.

**Comment by mhartington** [comment]
Hmm, they're working for me in iterm nightlies. What terminal are you using?

**Comment by mhartington** [comment]
Ah I see, this is for the terminal emulation in neovim. Alright, thanks for this

**Pull request merged**
